name: reuseable-workflow-caller
run-name: ${{ github.actor }} reuseable-workflow-caller

on:
  push:
    branches: none

  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: ./.github/workflows/reuseable-workflow-called.yml
    with:
      username: AnhVu
    secrets:
      token: ${{ secrets.TOKEN }}

  call-workflow-B:
    uses: ./.github/workflows/reuseable-workflow-called.yml
    with:
      username: Tokai
    secrets:
      token: ${{ secrets.TOKEN }}