name: Test
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build

    strategy:
      matrix:
        runs-on: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: npm install
      run: npm install

    - name: Create artifacts
      run: |
        mkdir -p dist/artifact-A
        echo "Lorem ipsum dolor sit amet" > dist/artifact-A/file-A.txt

    - name: Upload artifact A
      uses: actions/upload-artifact@v4
      with:
        name: Artifact-A-${{ matrix.runs-on }}
        path: dist/artifact-A

    # Test downloading a single artifact
    - name: Download artifact A
      uses: ./
      with:
        name: Artifact-A-${{ matrix.runs-on }}
        path: ~/dist

    - name: Verify successful download
      run: |
        $file1 = "~/dist/file-A.txt"
        if(!(Test-Path -path $file1)
        {
            Write-Error "Expected files do not exist"
        }
        if(!((Get-Content $file1) -ceq "Lorem ipsum dolor sit amet"))
        {
            Write-Error "File contents of downloaded artifacts are incorrect"
        }
      shell: pwsh