name: Node CI
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: npm install, build, and test
        run: |
          echo "This is 'npm install' command"
          echo "This is 'npm run build' command"
          echo "This is 'npm test' command"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md