name: Node CI
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create artifacts
        run: |
          mkdir -p path/to/artifact-A
          mkdir -p path/to/artifact-B
          echo "Lorem ipsum dolor sit amet" > path/to/artifact-A/file-A.txt
          echo "Hello world from file B" > path/to/artifact-B/file-B.txt

      - name: Upload artifact A
        uses: actions/upload-artifact@v4
        with:
          name: Artifact-A-${{ matrix.runs-on }}
          path: |
            path/to/artifact-A
      
      # Test downloading a single artifact
      - name: Download artifact A
        uses: ./
        with:
          name: Artifact-A-${{ matrix.runs-on }}
          path: some/new/path
      
      - name: Verify successful download
        run: |
          $file1 = "some/new/path/file-A.txt"
          if(!(Test-Path -path $file1)
          {
            Write-Error "Expected files do not exist"
          }
          if (!((Get-Content $file1) -ceq "Lorem ipsum dolor sit amet"))
          {
            Write-Error "File contents of downloaded artifacts are incorrect"
          }
        shell: pwsh